# Generated by Django 3.2.9 on 2021-12-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211212_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pesel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tel_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
