# Generated by Django 3.2.9 on 2021-12-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211212_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pesel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='tel_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
