# Generated by Django 3.2.9 on 2022-01-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_user'),
        ('users', '0004_auto_20211212_1100'),
    ]

    operations = [
    ]
