# Generated by Django 3.2.9 on 2022-01-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_0002_alter_profile_user_0004_auto_20211212_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='numer telefonu'),
        ),
    ]
